language: node_js
node_js:
  - "8.5.0"
cache: yarn
install:
  - yarn
script:
  - yarn verify
notifications:
  email: false
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: docs/build
  committer-from-gh: true
  on:
    branch: master