export interface ICommonSpec {
    minExponent: number;
    maxExponent: number;
}

export interface ICodeGenSpec extends ICommonSpec {
    operators: IPartialOperatorSpec[];
}

export interface IPartialOperatorSpec {
    fileNamePrefix: string;
    uncurriedTypeNamePrefix: string;
    curriedTypeNamePrefix: string;
    testTypeNamePrefix: string;
    specialCases: { [left: number]: string };
    compute: (left: number, right: number) => number;
}

export interface IOperatorSpec extends ICommonSpec, IPartialOperatorSpec {}

export interface IExponentSpec {
    value: number;
    type: string;
}

export function getExponents({ minExponent, maxExponent }: ICommonSpec): IExponentSpec[] {
    const exponents: IExponentSpec[] = [];
    for (let value = minExponent; value <= maxExponent; value++) {
        exponents.push({ value, type: `"${value}"` });
    }
    return exponents;
}

export function isExponent(exponent: number, { minExponent, maxExponent }: ICommonSpec): boolean {
    return exponent >= minExponent && exponent <= maxExponent && exponent === Math.floor(exponent);
}

export function genFileHeader(disableTslint: boolean = true): string[] {
    const header = ["// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.", ""];
    if (disableTslint) {
        header.push("// tslint:disable", "");
    }
    return header;
}

export function genImport(symbol: string, source: string): string[] {
    return [`import { ${symbol} } from "${source}";`, ""];
}

export function genUncurriedTypeName(spec: IOperatorSpec, left?: string | number, right?: string | number): string {
    const args = left !== undefined && right !== undefined ? `<${left}, ${right}>` : "";
    return `${spec.uncurriedTypeNamePrefix}Exponents${args}`;
}

export function genExponentName({ value }: IExponentSpec): string {
    if (value === 0) {
        return "Zero";
    }
    const sign = value < 0 ? "Neg" : "Pos";
    return `${sign}${Math.abs(value)}`;
}
