export const EXPONENTS = [-5, -4, -3, -2, -1, 0, 1, 2, 3, 4, 5];

export interface OperatorCodeGenOptions {
    fileNamePrefix: string;
    uncurriedTypeNamePrefix: string;
    curriedTypeNamePrefix: string;
    testTypeNamePrefix: string;
    specialCases: { [left: number]: string };
    compute: (left: number, right: number) => number;
}

export function genFileHeader(): string[] {
    return ["// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.", "", "// tslint:disable", ""];
}

export function genImport(symbols: string[], source: string): string {
    symbols.sort((first, second) => {
        if (first < second) {
            return -1;
        }
        if (first > second) {
            return 1;
        }
        return 0;
    });

    return `import { ${symbols.join(", ")} } from "${source}";`;
}

export function genUncurriedTypeName(options: OperatorCodeGenOptions, left?: string | number, right?: string | number) {
    const args = left !== undefined && right !== undefined ? `<${left}, ${right}>` : "";
    return `${options.uncurriedTypeNamePrefix}Exponents${args}`;
}

export function genValueName(value: number): string {
    if (value === 0) {
        return "0";
    }
    const sign = value < 0 ? "Negative" : "Positive";
    return `${sign}${Math.abs(value)}`;
}

export function indent(line: string) {
    return "    " + line;
}
