// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.

// tslint:disable

import { ArithmeticError, Exponent } from "./common";

export type AddExponents<L extends Exponent, R extends Exponent>
    = L extends -5 ? AddNegative5<R>
    : L extends -4 ? AddNegative4<R>
    : L extends -3 ? AddNegative3<R>
    : L extends -2 ? AddNegative2<R>
    : L extends -1 ? AddNegative1<R>
    : L extends 0 ? R
    : L extends 1 ? AddPositive1<R>
    : L extends 2 ? AddPositive2<R>
    : L extends 3 ? AddPositive3<R>
    : L extends 4 ? AddPositive4<R>
    : L extends 5 ? AddPositive5<R>
    : ArithmeticError;

export type AddNegative5<N extends Exponent>
    = N extends 0 ? -5
    : N extends 1 ? -4
    : N extends 2 ? -3
    : N extends 3 ? -2
    : N extends 4 ? -1
    : N extends 5 ? 0
    : ArithmeticError;

export type AddNegative4<N extends Exponent>
    = N extends -1 ? -5
    : N extends 0 ? -4
    : N extends 1 ? -3
    : N extends 2 ? -2
    : N extends 3 ? -1
    : N extends 4 ? 0
    : N extends 5 ? 1
    : ArithmeticError;

export type AddNegative3<N extends Exponent>
    = N extends -2 ? -5
    : N extends -1 ? -4
    : N extends 0 ? -3
    : N extends 1 ? -2
    : N extends 2 ? -1
    : N extends 3 ? 0
    : N extends 4 ? 1
    : N extends 5 ? 2
    : ArithmeticError;

export type AddNegative2<N extends Exponent>
    = N extends -3 ? -5
    : N extends -2 ? -4
    : N extends -1 ? -3
    : N extends 0 ? -2
    : N extends 1 ? -1
    : N extends 2 ? 0
    : N extends 3 ? 1
    : N extends 4 ? 2
    : N extends 5 ? 3
    : ArithmeticError;

export type AddNegative1<N extends Exponent>
    = N extends -4 ? -5
    : N extends -3 ? -4
    : N extends -2 ? -3
    : N extends -1 ? -2
    : N extends 0 ? -1
    : N extends 1 ? 0
    : N extends 2 ? 1
    : N extends 3 ? 2
    : N extends 4 ? 3
    : N extends 5 ? 4
    : ArithmeticError;

export type AddPositive1<N extends Exponent>
    = N extends -5 ? -4
    : N extends -4 ? -3
    : N extends -3 ? -2
    : N extends -2 ? -1
    : N extends -1 ? 0
    : N extends 0 ? 1
    : N extends 1 ? 2
    : N extends 2 ? 3
    : N extends 3 ? 4
    : N extends 4 ? 5
    : ArithmeticError;

export type AddPositive2<N extends Exponent>
    = N extends -5 ? -3
    : N extends -4 ? -2
    : N extends -3 ? -1
    : N extends -2 ? 0
    : N extends -1 ? 1
    : N extends 0 ? 2
    : N extends 1 ? 3
    : N extends 2 ? 4
    : N extends 3 ? 5
    : ArithmeticError;

export type AddPositive3<N extends Exponent>
    = N extends -5 ? -2
    : N extends -4 ? -1
    : N extends -3 ? 0
    : N extends -2 ? 1
    : N extends -1 ? 2
    : N extends 0 ? 3
    : N extends 1 ? 4
    : N extends 2 ? 5
    : ArithmeticError;

export type AddPositive4<N extends Exponent>
    = N extends -5 ? -1
    : N extends -4 ? 0
    : N extends -3 ? 1
    : N extends -2 ? 2
    : N extends -1 ? 3
    : N extends 0 ? 4
    : N extends 1 ? 5
    : ArithmeticError;

export type AddPositive5<N extends Exponent>
    = N extends -5 ? 0
    : N extends -4 ? 1
    : N extends -3 ? 2
    : N extends -2 ? 3
    : N extends -1 ? 4
    : N extends 0 ? 5
    : ArithmeticError;
