// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.

export type MinExponent = -5;
export const MinExponent: MinExponent = -5;

export type MaxExponent = 5;
export const MaxExponent: MaxExponent = 5;

export type Exponent = -5 | -4 | -3 | -2 | -1 | 0 | 1 | 2 | 3 | 4 | 5;

export type ArithmeticError = "UnitError" & "Arithmetic out of bounds";
export const ArithmeticError = "Arithmetic out of bounds";
export type IsArithmeticError<T> = T extends ArithmeticError ? true : false;
